### ISSUE TITLE
zebra is not compatible to Neos 8.3 out of the box

### ISSUE THREAD

**Issue by johannessteu** [networkteam/zebra#5]
The [injected path](https://github.com/networkteam/zebra/blob/main/src/utils/helper.ts#L184) to css and js files for `neos/neos-ui-compiled` in version ~8.3 are not valid.

Current path:
/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Styles/Host.css

Should be:
http://localhost:3000/_Resources/Static/Packages/Neos.Neos.Ui.Compiled/Build/Host.css

To avoid different releases we could add the Neos Version to the documentInformation here inside the ContentAPI package
and use some helper to get the currently version installed
```
Neos:
  Neos:
    Ui:
      documentNodeInformation:
        version: 8.3.0
```

Based on this information it would be possible to switch paths
